# Type stubs for dearpygui
from typing import Any, Callable, Optional, Tuple, Union

def create_viewport(title: str, width: int, height: int, **kwargs) -> None: ...
def bind_theme(theme: int) -> None: ...
def add_font(file: str, size: float) -> int: ...
def bind_font(font: int) -> None: ...
# ... add other needed stubs 