on:
  workflow_dispatch:
  push:
    branches:
      - main
      - buidGridset
  pull_request:

jobs:
  build:
    runs-on: windows-latest      
    steps:
    - uses: actions/checkout@v3
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v4.7.1
      with:
        python-version: "3.11.4"
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install dependencies
      run: |
        poetry install
    - name: Inject secrets into environment
      shell: bash
      run: |
        echo "MICROSOFT_TOKEN=${{ secrets.MICROSOFT_TOKEN }}" >> $GITHUB_ENV
        echo "MICROSOFT_REGION=${{ secrets.MICROSOFT_REGION }}" >> $GITHUB_ENV
        printf "GOOGLE_CREDS_JSON=%s\n" "${{ secrets.GOOGLE_CREDS_JSON }}" >> $GITHUB_ENV
        echo "MICROSOFT_TOKEN_TRANS=${{ secrets.MICROSOFT_TOKEN_TRANS }}" >> $GITHUB_ENV   
        echo "CONFIG_ENCRYPTION_KEY: ${{ secrets.CONFIG_ENCRYPTION_KEY }}" >> $GITHUB_ENV   
        poetry run python encrypt_config.py
    - name: Build Apps
      run: |
        poetry run python -c "import site; print(site.getsitepackages()[0])"
        .\build_executable.bat
      env:
        CONFIG_ENCRYPTION_KEY: ${{ secrets.CONFIG_ENCRYPTION_KEY }}
        MICROSOFT_TOKEN: ${{ secrets.MICROSOFT_TOKEN }}
        MICROSOFT_REGION: ${{ secrets.MICROSOFT_REGION }}
        GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
        MICROSOFT_TOKEN_TRANS: ${{ secrets.MICROSOFT_TOKEN_TRANS }}
    - name: Upload Installer
      uses: actions/upload-artifact@v3
      with:
        name: 'Windows Release'
        path: 'Output\AACSpeakHelper.exe'
